
version: "3"

services:
  bot:
    build: .
    env_file: .env
    depends_on:
      - mongo
      - keydb
  mongo:
    image: mongo
    ports:
     - "27017:27017"
  keydb:
    image: eqalpha/keydb
    ports:
      - "6379:6379"
